on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Quay
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QUAY_UNAME }}
          password: ${{ secrets.QUAY_PASSWD }}
          registry: quay.io

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: toshibhtr/discord-annoyance:latest
          file: Containerfile
